pipeline {
    agent any

    stages {
        stage('clone project') {
            steps {
                git branch: 'main', url: 'https://github.com/vinaykumarshetkar/vinayproj.git'
            }
        }

        stage('clean') {
            steps {
                sh 'mvn clean'
            }
        }

        stage('compile') {
            steps {
                sh 'mvn compile'
            }
        }

        stage('test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('build') {
            steps {
                sh 'mvn clean install'
            }
        }
	}
	    stages {
        stage('SMTP Test') {
            steps {
                sh 'telnet smtp.gmail.com 587 || true'
            }
        }
		}
	post {
        success {
            emailext(
                to: 'vinay.reports.abc@gmail.com',
                subject: "SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: "Build succeeded. Check: ${env.BUILD_URL}"
            )
        }

        failure {
            emailext(
                to: 'vinay.reports.abc@gmail.com',
                subject: "FAILURE: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: "Build failed. Check: ${env.BUILD_URL}"
            )
        }
    }
    
}
